#!/usr/bin/env node
"use strict";
const replace = require("replace-in-file");

if (!process.argv[2]) {
  throw "Name of new module undefined ";
} else {
  console.log(`new_name: ${process.argv[2]}`)
}

async function init(new_name) {
  const options = {
    files: process.cwd() + "/**",
    disableGlobs: false,
    ignore: process.cwd() + "/\.factory/**",
    from: /webresto-module-starter/g,
    to: new_name,
    countMatches: true
  };

  try {
    const results = await replace(options);
    console.log("Replacement results:", results);
  } catch (error) {
    console.error("Error occurred:", error);
  }
}

init(process.argv[2]);
