#!/usr/bin/env node
"use strict";
const replace = require("replace-in-file");

const fs = require("fs");

if (fs.existsSync(process.cwd() + "/module_init")) {
  throw "Please use this factory only in module root directory"
}

if (!process.argv[2]) {
  throw "Name of new module undefined ";
} else {
  console.log(`new_name: ${process.argv[2]}`)
}

async function init(new_name) {
  const options = {
    files: process.cwd() + "/**",
    //dry: true,
    ignore: [ 
      process.cwd() + "/.factory/**",
      process.cwd() + "/node_modules/**",
    ],
    from: /webresto-module-starter/g,
    to: new_name,
    countMatches: true
  };

  try {
    const results = await replace(options);
    console.log("Replacement results:", results);
    fs.rmSync(process.cwd()+"/.factory", { recursive: true, force: true });
    fs.rmSync(process.cwd()+"/.git", { recursive: true, force: true });
  } catch (error) {
    console.error("Error occurred:", error);
  }
}

init(process.argv[2]);
